name: Twitter Auto-Post Bot

on:
  schedule:
    - cron: '0 * * * *' # كينشر مرة كل ساعة
  workflow_dispatch: # كيخليك تخدمو يدوياً إلا بغيتي تجرب

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install tweepy requests beautifulsoup4 groq

      - name: Run Auto-Post Bot
        env:
          # هنا ربطنا السميات اللي فـ GitHub Secrets مع الكود
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          SMART_LINK: ${{ secrets.SMART_LINK }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python bot_cron.py
